### ISSUE TITLE
Make secret rotation lambda templates available on GitHub

### ISSUE THREAD

**Issue by hwatts** [awsdocs/aws-secrets-manager-docs#2]
It's a bit of a pain to have to create a cloudformation stack just to see the sample code for creating custom lambdas. Would someone be able to put these onto GitHub and reference the source in the serverlessrepo and the docs?

I'm referring to this doc:
https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-create-generic-template.html

And one of the stacks in the serverless repo is linked below:

https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:297356227824:applications~SecretsManagerRotationTemplate

Thanks in advance. Happy to raise a PR to contribute to the docs, but it's not my code to publish...

**Comment by bisdavid** [comment]
I'll talk to the engineering team and find out what we can do about publishing these.  Thanks for the suggestion.

**Comment by bisdavid** [comment]
The engineering team is investigating what it would take to post them to GitHub in a way that would enable them to accept pull requests directly.   I will post them in my documentation in the interim, with the limitation that pull requests would be specifically for the docs - not for the original template.

**Comment by bisdavid** [comment]
In the interim, I have published them here in github as part of the documentation.  Note that you must still extract them from the doc markup text. An easier way to get the source directly is to go to these web pages and use the copy icon at the top of each code page.  Then paste into your own text editor and you're done! 

https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html
