### ISSUE TITLE
Retreive permissions error

### ISSUE THREAD

**Issue by justinabrahms** [awsdocs/aws-secrets-manager-docs#4]
At https://github.com/awsdocs/aws-secrets-manager-docs/blob/master/doc_source/manage_retrieve-secret.md

> secretsmanager:GetSecretValue — to retrieve the non-encrypted parts of the secret 
> secretsmanager:GetSecretValue – to retrieve the encrypted part of the secret

I suspect these are different permissions and there's a typo somewhere?

**Comment by hwatts** [comment]
Agreed - should be  `secretsmanager:DescribeSecret` I would think.

**Comment by bisdavid** [comment]
You folks are right, of course.  Good catch!  I've fixed this in the source, and I'm pushing the change thru the publishing pipeline now.
